version: "3.9"

services:
  backend:
    build: .
    working_dir: /app/backend
    command: python -m app.run
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app/backend
      - ./backend/data:/app/backend/data
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
